---
title: "590R Final"
format: html
excute:
  error:true
  eval:true
---

install.packages("gtsummary")
install.packages("tidyverse")

```{r}

library(gtsummary)
library(tidyverse)
chocolate <- read_csv(here::here("chocolate data", "chocolate.csv"))
```

```{r}
#table
#| label: tbl-one
#| tbl-cap: "Chocolate Company Information" 
tbl_summary( 
  chocolate,
  by = rating,
  include = c(country_of_bean_origin),
  label = list(
    country_of_bean_origin ~ "Country of Bean Origin"),
  missing_text = "Missing")

```

```{r}
#regression 
logistic_model <- glm(as.factor(chocolate$rating)~ cocoa_percent + review_date,
									 data = chocolate, family = binomial())
```

```{r}
#figure
#| label: fig-hist
#| fig-cap: "Chocolate Rating"
hist(chocolate$rating)
```
@fig-hist contains a histogram and @tbl-one a table.

```{r}
#function
x <- c(chocolate$rating)
rating_mean<- function(x) {
  n <- length(x)
  mean_val <- sum(x) / n
  return(mean_val)}
```
The `echo: false` option disables the printing of code (only output is displayed).
